SpotifyWebAPI/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SpotifyWebAPI.Service.Models;
using SpotifyWebAPI.Service.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpotifyWebAPI.Controllers
{
    public class ArtistController : Controller
    {
        private readonly ISpotifyService _spotifyService;
        private readonly ISpotifyAccountService _spotifyAccountService;
        private readonly IConfiguration _configuration;
        public ArtistController(ISpotifyService spotifyService, ISpotifyAccountService spotifyAccountService, IConfiguration configuration)
        {
            _spotifyService = spotifyService;
            _spotifyAccountService = spotifyAccountService;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            ViewModel vm = new ViewModel();
            vm.SearchArtist = null;
            return View(vm);
        }

        [HttpPost]
        public ActionResult Index(string txtArtist)
        {
            ViewModel vm = new ViewModel();
            vm.SearchArtist = GetSearchArtist(txtArtist, "us");

            return View(vm);
        }
        private async Task<IEnumerable<SearchArtist>> GetSearchArtist(string query, string market)
        {
            try
            {
                var token = await _spotifyAccountService.GetToken(_configuration["Spotify:ClientId"], _configuration["Spotify:ClientSecret"]);

                var search = await _spotifyService.SearchArtist(query, market, 10, token);

                return search;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);
                return Enumerable.Empty<SearchArtist>();
            }
        }
    }
}

SpotifyWebAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SpotifyWebAPI.Service.Models;
using SpotifyWebAPI.Service.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpotifyWebAPI.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpotifyWebAPI/Controllers/ReleaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SpotifyWebAPI.Service.Models;
using SpotifyWebAPI.Service.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpotifyWebAPI.Controllers
{
    public class ReleaseController : Controller
    {
        private readonly ISpotifyService _spotifyService;
        private readonly ISpotifyAccountService _spotifyAccountService;
        private readonly IConfiguration _configuration;
        public ReleaseController(ISpotifyService spotifyService, ISpotifyAccountService spotifyAccountService, IConfiguration configuration)
        {
            _spotifyService = spotifyService;
            _spotifyAccountService = spotifyAccountService;
            _configuration = configuration;
        }
        
        public IActionResult Index()
        {
            ViewModel vm = new ViewModel();
            vm.GetReleases = GetReleases();

            return View(vm);
        }
        private async Task<IEnumerable<Release>> GetReleases()
        {

            try
            {
                var token = await _spotifyAccountService.GetToken(_configuration["Spotify:ClientId"], _configuration["Spotify:ClientSecret"]);

                var newReleases = await _spotifyService.GetNewReleases("TR", 18, token);


                return newReleases;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);

                return Enumerable.Empty<Release>();
            }
        }
    }
}

SpotifyWebAPI/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SpotifyWebAPI.Service.Models;
using SpotifyWebAPI.Service.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpotifyWebAPI.Controllers
{
    public class SongController : Controller
    {
        private readonly ISpotifyService _spotifyService;
        private readonly ISpotifyAccountService _spotifyAccountService;
        private readonly IConfiguration _configuration;
        public SongController(ISpotifyService spotifyService, ISpotifyAccountService spotifyAccountService, IConfiguration configuration)
        {
            _spotifyService = spotifyService;
            _spotifyAccountService = spotifyAccountService;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            ViewModel vm = new ViewModel();
            vm.Search = null;
            return View(vm);
        }

        [HttpPost]
        public ActionResult Index(string txtSong)
        {
            ViewModel vm = new ViewModel();
            vm.Search = GetSearch(txtSong);

            return View(vm);
        }
        private async Task<IEnumerable<Search>> GetSearch(string query)
        {
            try
            {
                var token = await _spotifyAccountService.GetToken(_configuration["Spotify:ClientId"], _configuration["Spotify:ClientSecret"]);

                var search = await _spotifyService.Search(query, "us", 10, token);

                return search;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);
                return Enumerable.Empty<Search>();
            }
        }
    }
}

SpotifyWebAPI/Views/Artist/Index.cshtml
@model ViewModel


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Index", "Artist"))
            {
                @Html.TextBox("txtArtist")
                <input type="submit" value="Ara" />
            }
        </div>

        @if (Model.SearchArtist != null)
        {
            @foreach (var searchResult in Model.SearchArtist.Result)
            {
                @if (searchResult.Followers > 50000)
                {
                    <div class="col-md-4" style="height:600px">
                        <div class="card-body">
                            <h4 class="card-title">Şarkıcı Adı : @Html.DisplayFor(x => searchResult.Name)</h4>
                            <h5>Tür : @Html.DisplayFor(x => searchResult.Genres)</h5>
                            <h6>Takipçi Sayısı : @Html.DisplayFor(x => searchResult.Followers)</h6>
                            <a href="@Html.DisplayFor(x=> searchResult.Link)">Sanatçıya Git</a>
                            <img style="width:100%;height:auto" src="@Html.DisplayFor(x => searchResult.Image)" />
                        </div>
                    </div>
                }
            }
        }


    </div>

SpotifyWebAPI/Views/Home/Index.cshtml
@model ViewModel
@{
    ViewData["Title"] = "Anasayfa";
}

<div class="row">

   Menüleri Kullanarak Sitede Gezebilirsiniz.

</div>

SpotifyWebAPI/Views/Release/Index.cshtml
@model ViewModel

<div class="row">
    @if (Model.GetReleases.Result.Count() > 0)
    {
        @foreach (var item in Model.GetReleases.Result)
        {
            <div class="col-md-3" style="height:600px">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Artists)</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.Name)</h6>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Date)</p>
                    <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" style="width:100%" alt="Resim" />
                    <a href="@Html.DisplayFor(modelItem => item.Link)" target="_blank">Hemen Dinle</a>
                </div>
            </div>
        }
    }
</div>

SpotifyWebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpotifyWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SpotifyWebAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Sanatçı Ara</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Müzik Ara</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Release" asp-action="Index">Son Çıkan Albümler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SpotifyWebAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SpotifyWebAPI/Views/Song/Index.cshtml
@model ViewModel

<div class="row">

    <div class="col-md-12">
        @using (Html.BeginForm("Index", "Song"))
        {
            @Html.TextBox("txtSong")
            <input type="submit" value="Ara" />
        }
    </div>
    @if (Model.Search != null)
    {
        @if (Model.Search.Result.Count() > 0)
        {
            @foreach (var searchResult in Model.Search.Result)
            {
                <div class="col-md-3" style="height:600px">
                    <div class="card-body">
                        <h4 class="card-title">Şarkı Adı : @Html.DisplayFor(x => searchResult.Name)</h4>
                        <h5>Sanatçılar : @Html.DisplayFor(x => searchResult.Artists)</h5>
                        <h6>Çıkış Tarihi : @Html.DisplayFor(x => searchResult.ReleaseDate)</h6>
                        <a href="@Html.DisplayFor(x=> searchResult.Link)">Hemen Dinle</a>
                        <img style="width:100%;height:auto" src="@Html.DisplayFor(x => searchResult.Image)" />
                    </div>
                </div>
            }
        }
    }


</div>